# Build settings
build:
  functions: functions
  publish: build
  # Inline lifecycle hooks
  lifecycle:
    onInit:
      - echo "starting the build"
    onPreBuild:
      - echo "Do thing before build"
    onBuild:
      - npm run build
    onPostBuild:
      - echo "Do thing after build"
    onSuccess:
      - echo "Ending the build"

# Build plugins
plugins:
  # Local plugin
  - type: ./plugins/one
    config:
      foo: bar
  # Serverless framework plugin
  - type: ./plugins/serverless
    config:
      path: ./backend
      AWS_ACCESS_KEY_ID: ${env:MY_AWS_KEY}
      AWS_SECRET_ACCESS_KEY: ${env:MY_AWS_ACCESS_KEY}
