# Build settings
build:
  functions: functions
  publish: build
  # Inline lifecycle hooks
  lifecycle:
    init:
      - echo "starting the build"
    preBuild:
      - echo "Do thing before build"
    build:
      - npm run build
    postBuild:
      - echo "Do thing after build"
    finally:
      - echo "Ending the build"

# Build plugins
plugins:
  # Local plugin
  - type: ./plugins/one
    config:
      foo: bar
  # sitemap plugin
  - type: '@netlify/plugin-sitemap'
